### ISSUE TITLE
Spread operator does not work

### ISSUE THREAD

**Issue by ahamedali95** [learn-co-curriculum/combine-reducers#10]
>`case "ADD_AUTHOR":
  return {
    ...state,
    authors: [...state.authors, action.author]
  };`

Here, you are copying over the properties that are not changing(i,.e., books) but the spread operator does not work in this case. The books property will still have a reference to the array exists in the old state. You could do something like this:

>`case "ADD_AUTHOR":
  return {
    ...state,
    books: [...state.books],
    authors: [...state.authors, action.author]
  };`

**Comment by ahamedali95** [comment]
please update the post

**Comment by maxwellbenton** [comment]
Hi @ahamedali95,

Thank you for spotting this and providing feedback. We've updated this lesson's code snippets and added an additional message regarding deep copies and links to further info on immutability, which should resolve this issue.

Thank you for contributing!
