### ISSUE TITLE
Stray asterisks in this paragraph

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/combine-reducers#11]
Replace the first asterisk with an underscore, and the second asterisked word should just be in italics, with no preceding underscore:
"In the new "ADD*BOOK" case, we're checking to see if an authorName matches with the name dispatches from the BookInput component. If the name already exists, state is returned unchanged. If the name is not present, it is added to the author array. Use the example above to modify the manageAuthorsAndBooks reducer and you can see the effect. We have two separate forms, one for adding just authors, and one that adds books _and* authors."

Thank you.

**Comment by maxwellbenton** [comment]
Thanks again @ValerieHMoore,

These errors should now be fixed.
