### ISSUE TITLE
Confusing Structure

### ISSUE THREAD

**Issue by darrendaz** [learn-co-curriculum/combine-reducers#12]
Code snippets for `booksReducer` and `authorsReducer` should mention that they are still in the same `manageAuthorsAndBooks` .js file. There were no ellipses in the code blocks so I assumed that they were newly created files.

**Comment by maxwellbenton** [comment]
Hi @darrendaz,

Thank you for this feedback. We've updated this lesson's Readme and added some messaging on file structure, as well as ellipses to further indicate that everything is in one file, which should prevent confusion in the future.

Thank you for contributing to this lesson!
