### ISSUE TITLE
default code does not match readme default code. 

### ISSUE THREAD

**Issue by andrew-lewell** [learn-co-curriculum/combine-reducers#20]
The readme default reducer includes author in book actions and book in author actions for immutability. This is not reflected in the actual code in the lab.

**Comment by VirgilCantu** [comment]
This may have been fixed in a commit by Sdcrouse, but I believe the commit was not merged since @andrew-lewell is correct, this is still not reflected in the actual code in the lab.

**Comment by graciemcguire** [comment]
Hello we just fixed this issue. Thanks for flagging!

**Comment by VirgilCantu** [comment]
Thank you!
