### ISSUE TITLE
Code Snippets have no File/Folder locations 

### ISSUE THREAD

**Issue by doosemavis** [learn-co-curriculum/combine-reducers#29]
Hi there, 

Just wanted to pass this along, I noticed in this code along its quite difficult to understand where these code changes are going and being implemented when the snippets themselves don't have any of the file paths at the top for reference.  

I hope this could be useful to cohort members in the future! :) 

Sincerely,
MD

**Comment by graciemcguire** [comment]
We have updated to reflect the readme. Thanks!
