### ISSUE TITLE
no repo to download?

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/combine-reducers#5]
This lab feels lazily done - There should be a code repo for students to follow along with. Why not also update the lab so that the code doesn't "have a bug in it."

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials to be a codealong, updated the readme examples and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
