### ISSUE TITLE
Mismatch variable names in last code snippet

### ISSUE THREAD

**Issue by pawlkris** [learn-co-curriculum/combine-reducers#6]
Dispatch code in paragraph before last code snippet is:

```store.dispatch({ action: 'ADD_BOOK', book: { title: 'huck finn', **authorName**: 'Mark Twain' } });```

then in last code snippet, authorsReducer/case 'ADD_BOOK'

```case "ADD_BOOK":
      let existingAuthor = state.filter(author => author.name === **action.author.name**)
      if(!existingAuthor) {
        return state.concat(action.author);
      } else {
        return state
      }```

**Comment by realAndrewCohn** [comment]
Hi Paul,

Thank you for submitting an issue. I've updated the readme to fix the error in the readme. See this commit https://github.com/learn-co-curriculum/combine-reducers/commit/a78138eed49d318fba316dc0bd893a60d8dbe871 for the fix
