### ISSUE TITLE
Object.assign is mutating the existing 'state' object

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/combine-reducers#7]
In many examples a pattern like this is used:
```
case "ADD_BOOK":
  return Object.assign(state, {
    books: state.books.concat(action.book)
});
```
However, this modifies the existing `state` object which is bad practice. `Object.assign` should take an empty object as its first parameter (e.g. `Object.assign({}, state, { ...`) so that existing state remains un-mutated.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback. You are absolutely correct.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
