### ISSUE TITLE
Reducer File Missing uuid Function

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/combine-reducers#8]
During the rewrite of the the `manageAuthorsAndBooks` file, when adding the "ADD_BOOK" case to the `authorsReducer`, they make use of the `uuid()` function even though it was never introduced or imported.

This can be solved by adding this import:

`import uuid from 'uuid'`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
