### ISSUE TITLE
Incorrect sample code

### ISSUE THREAD

**Issue by BrownCow371** [learn-co-curriculum/combine-reducers#9]
Hello!  In the initial combined reducer, I think the following:

    case "REMOVE_AUTHOR":
      idx = state.authors.indexOf(action.id);
      return {
        ...state,
        authors: [state.authors.slice(0, idx), state.authors.slice(idx + 1)]
      };

should be:

    case "REMOVE_AUTHOR":
      idx = state.authors.indexOf(action.id);
      return {
        ...state,
        authors: [...state.authors.slice(0, idx), ...state.authors.slice(idx + 1)]
      };

else the function returns an array for authors that consists of 2 arrays (one for the first slice and one for the second) instead of a single array. 

Same goes for the REMOVE_BOOK code.  Thanks!

**Comment by julianjohannesen** [comment]
Nice catch! I was just coming here to report the same thing.

**Comment by maxwellbenton** [comment]
Hi @BrownCow371,

Thank you for spotting this and providing feedback. This error has been fixed in the readme and provided code.

Thank you for contributing to a Learn lesson!
